### ISSUE TITLE
add db driver, make superset can connect to elasticsearch

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-superset#13]

**Comment by zengxc-1996** [comment]
[install driver](https://superset.apache.org/docs/databases/installing-database-drivers)

1.  change container permissive  
     update compose file
![image](https://user-images.githubusercontent.com/63622990/126415870-7b10664a-8a3b-47d0-ba42-8bbbe65de285.png)

2. add requirements file
![image](https://user-images.githubusercontent.com/63622990/126416057-cb050421-f5c9-4815-a763-132dc304e0e9.png)

3. docker-compose down and docker-compose up ,It will automatically install and start.

when container starting, To perform the init.sh, Init. sh is called to execute docker-bootstrap.sh.

need remove the volumes,Otherwise init.sh does not execute.

4.  The official solution is to reset the mirror, but I failed to verify it successfully.

![image](https://user-images.githubusercontent.com/63622990/126416525-d4e3250a-e144-47e3-9c30-f4cf07fa11d1.png)

```
[root@iZj6cci77g4mwnlof8jcjdZ superset]# docker-compose build --force-rm
redis uses an image, skipping
db uses an image, skipping
superset uses an image, skipping
superset-init uses an image, skipping
superset-worker uses an image, skipping
superset-worker-beat uses an image, skipping
```
